### ISSUE TITLE
Python text-adventure issue

### ISSUE THREAD

**Issue by Redlock9** [Redlock9/text-adventure#1]
I'm trying to write my first python program and have some syntax problems. Please help me. When I'm running the code it will show me the following output.

[{
	"resource": "/Users/.../Visual Studio Code Text-Advanture /text.py",
	"owner": "_generated_diagnostic_collection_name_#1",
	"severity": 8,
	"message": "Unindent amount does not match previous indent",
	"source": "Pylance",
	"startLineNumber": 35,
	"startColumn": 9,
	"endLineNumber": 35,
	"endColumn": 9
}]

[{
	"resource": "/Users/.../Visual Studio Code Text-Advanture /text.py",
	"owner": "_generated_diagnostic_collection_name_#1",
	"severity": 8,
	"message": "Unindent amount does not match previous indent",
	"source": "Pylance",
	"startLineNumber": 38,
	"startColumn": 9,
	"endLineNumber": 38,
	"endColumn": 9
}]

**Comment by Redlock9** [comment]
<img width="1440" alt="Bildschirmfoto 2022-09-05 um 10 42 26" src="https://user-images.githubusercontent.com/96795713/188407342-3eb232b2-14b4-4442-8581-0241e7781b88.png">

**Comment by Suryasai369** [comment]
Have you  checked the Indentations. In line 36, that line not in previous IF block and not in parallel if block. Hence, change indent and check your code.

**Comment by Suryasai369** [comment]
I am trying to make Pull Request but I can't understand your code due to non-english. If you explain what you are trying to achieve I can help with your project

**Comment by Pedrossann** [comment]
This is my first contribution so hopefully I did it the right way. But just to be sure: When I remake all the tab and spaces in the code it run without problem, so the reason why it wasn't working was. that you had sometimes 3 or 5 spaces before the if and elif command.
